#分布式配置中心，必须保存为UTF-8编码
spring:
  profiles:
    active:
    - dev

---
server:
  port: 8201
spring:
  profiles: dev       #开发环境
  application:
    name: cloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8888/eureka
---
server:
  port: 8202
spring:
  profiles: test      #测试环境
  application:
    name: cloud-config-client1234
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8888/eureka
